# \<Template Notebook\>

## Environment Requirements

**Python**: `v3.14.2`

## Required imports

In [ ]:
from google.colab import drive
from scipy.stats import uniform, binom, norm, poisson, expon, t, lognorm
# from pathlib import Path

import numpy as np  
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Data sources

### Mounting Google Drive

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive

### Get DataFrame

In [3]:
def get_df(file_name: str, **read_csv_options):
  """Get DataFrame from personal Google Drive CSV file"""
  gd_dir_location = '/content/drive/My Drive/Colab Notebooks/data/learning/'
  return pd.read_csv(gd_dir_location + file_name, index_col=0, **read_csv_options)

In [4]:
# Used for local data
#
# def get_df(file_name: str):
#   filepath = Path("..")/"data"/file_name
#   return pd.read_csv(filepath, index_col=0)

### Sources

In [5]:
amir_deals = get_df('amir_deals.csv')
world_happiness = get_df('world_happiness.csv')

## \<Sub heading\>

Subheading description.

In [10]:
amir_deals.head()

     product   client status   amount  num_users
1  Product F  Current    Won  7389.52         19
2  Product C      New    Won  4493.01         43
3  Product B      New    Won  5738.09         87
4  Product I  Current    Won  2591.24         83
5  Product E  Current    Won  6622.97         17

In [16]:
amir_deals['amount_per_user'] = round(amir_deals['amount'] / amir_deals['num_users'], 2)
amir_deals.head()

     product   client status   amount  num_users  amount_per_user
1  Product F  Current    Won  7389.52         19           388.92
2  Product C      New    Won  4493.01         43           104.49
3  Product B      New    Won  5738.09         87            65.96
4  Product I  Current    Won  2591.24         83            31.22
5  Product E  Current    Won  6622.97         17           389.59